spring.application.name: data

instance.id: ${random.value}

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    #leaseRenewalIntervalInSeconds: 1
    #leaseExpirationDurationInSeconds: 1
    metadata-map:
     instanceId: ${instance.id}


server.port: 8080
management.port: 8081
management.security.enabled: false
---
spring:
  profiles: devclient1
server.port: 8083
management.port: 8084
---
spring:
  profiles: devclient2
server.port: 8085
management.port: 8086
---
spring:
  profiles: devclient3
server.port: 8087
management.port: 8088

