eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  #prefix: /api
  routes:
    product:
      path: /catalog/**
      #serviceId es el identificador del servicio en Eureka
      serviceId: PRODUCT_CATALOG
      retryable: true
    customer:
      path: /customer/**
      serviceId: CUSTOMER_SERVICE
      retryable: true

spring:
  application:
    name: zuul-server