management.security.enabled: false
spring.application.name: customer_service

instance.id: ${random.value}

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
     instanceId: ${instance.id}
